services:
    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        environment:
            - MH_STORAGE=maildir
        restart: unless-stopped

    mariadb:
        image: mariadb:latest
        restart: always
        container_name: sadaqa_db_container
        ports:
            - "3306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USER}
        volumes:
            - dbsadaqa:/var/lib/mysql
volumes:
    dbsadaqa:
